//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fmkclient.net.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TRIFORK SERVICES A/S")]
        public string IDCardIssuer {
            get {
                return ((string)(this["IDCardIssuer"]));
            }
            set {
                this["IDCardIssuer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Trifork")]
        public string SosiCareProviderName {
            get {
                return ((string)(this["SosiCareProviderName"]));
            }
            set {
                this["SosiCareProviderName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20921897")]
        public string SosiCareProviderCvr {
            get {
                return ((string)(this["SosiCareProviderCvr"]));
            }
            set {
                this["SosiCareProviderCvr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fmkclient.net")]
        public string ITSystemName {
            get {
                return ((string)(this["ITSystemName"]));
            }
            set {
                this["ITSystemName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test1234")]
        public string CERTPass {
            get {
                return ((string)(this["CERTPass"]));
            }
            set {
                this["CERTPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Læge")]
        public string UserRole {
            get {
                return ((string)(this["UserRole"]));
            }
            set {
                this["UserRole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kpn@trifork.com")]
        public string UserEmail {
            get {
                return ((string)(this["UserEmail"]));
            }
            set {
                this["UserEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Trifork")]
        public string WhitelistSystemOwner {
            get {
                return ((string)(this["WhitelistSystemOwner"]));
            }
            set {
                this["WhitelistSystemOwner"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fmkclient.net")]
        public string WhitelistSystemName {
            get {
                return ((string)(this["WhitelistSystemName"]));
            }
            set {
                this["WhitelistSystemName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Trifork")]
        public string WhitelistOrgUsingName {
            get {
                return ((string)(this["WhitelistOrgUsingName"]));
            }
            set {
                this["WhitelistOrgUsingName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2")]
        public string WhitelistSystemVersion {
            get {
                return ((string)(this["WhitelistSystemVersion"]));
            }
            set {
                this["WhitelistSystemVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Trifork")]
        public string WhitelistOrgResponsibleName {
            get {
                return ((string)(this["WhitelistOrgResponsibleName"]));
            }
            set {
                this["WhitelistOrgResponsibleName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20921897")]
        public string WhitelistOrgCVR {
            get {
                return ((string)(this["WhitelistOrgCVR"]));
            }
            set {
                this["WhitelistOrgCVR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Læge")]
        public string WhitelistRequestedRole {
            get {
                return ((string)(this["WhitelistRequestedRole"]));
            }
            set {
                this["WhitelistRequestedRole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20921897")]
        public string CERTCVR {
            get {
                return ((string)(this["CERTCVR"]));
            }
            set {
                this["CERTCVR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://test2-cnsp.ekstern-test.nspop.dk:8080/sts/services/SecurityTokenService")]
        public string STSUrl {
            get {
                return ((string)(this["STSUrl"]));
            }
            set {
                this["STSUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lene")]
        public string UserGivenName {
            get {
                return ((string)(this["UserGivenName"]));
            }
            set {
                this["UserGivenName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rasmussen")]
        public string UserSurName {
            get {
                return ((string)(this["UserSurName"]));
            }
            set {
                this["UserSurName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2611223938")]
        public string UserCpr {
            get {
                return ((string)(this["UserCpr"]));
            }
            set {
                this["UserCpr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("K4CQR")]
        public string UserAuthCode {
            get {
                return ((string)(this["UserAuthCode"]));
            }
            set {
                this["UserAuthCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8001149")]
        public string WhitelistYdernummer {
            get {
                return ((string)(this["WhitelistYdernummer"]));
            }
            set {
                this["WhitelistYdernummer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lene Rasmussen")]
        public string CERTGivenName {
            get {
                return ((string)(this["CERTGivenName"]));
            }
            set {
                this["CERTGivenName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Projects\\fmkclient146.net\\cert\\LeneRasmussen.p12")]
        public string CERTPath {
            get {
                return ((string)(this["CERTPath"]));
            }
            set {
                this["CERTPath"] = value;
            }
        }
    }
}
